terraform {
  required_providers {
    supercargo = {
      source  = "supercargo-dev/supercargo"
      version = "= 0.0.1-alpha.2"
    }
    google = {
      source  = "hashicorp/google"
      version = "~> 7.0"
    }
  }
}

provider "supercargo" {
  hub_address = "api.supercargo.example.com:443"
}

provider "google" {
  project = "my-gcp-project"
  region  = "europe-west1"
}

locals {
  # Parse the central Data Product manifest generated by the coding agent
  manifest = yamldecode(file("${path.module}/dataproduct.yaml"))

  # Automatically map each output port to its corresponding schema JSON file.
  # The agent generates schemas in the /schemas folder named by the port name.
  contracts = {
    for port in local.manifest.output_ports : port.contract.urn => {
      version     = port.contract.version
      schema_json = file("${path.module}/schemas/${port.name}.${port.contract.version}.bigquery.json")
    }
    if port.contract != null
  }
}

module "customer_telemetry" {
  source = "../../modules/data_product"

  # 1. Logical configuration (Hub)
  manifest_file = "${path.module}/dataproduct.yaml"
  contracts     = local.contracts

  # 2. Physical infrastructure (GCP Data Plane)
  project_id          = "my-gcp-project"
  region              = "europe-west1"
  bigquery_dataset_id = "customer_telemetry"

  # Gateway container configuration
  image          = "gcr.io/supercargo/gateway:latest"
  hub_address    = "api.supercargo.example.com:443"
  kms_address    = "kms.supercargo.example.com:443"
  master_key_uri = "gcp-kms://projects/..."

  # Ensure the gateway enforces authentication
  auth_enforce = true
}

output "gateway_url" {
  description = "The URL of the deployed Cloud Run Gateway"
  value       = module.customer_telemetry.gateway_url
}

output "product_urn" {
  description = "The Supercargo URN of the registered product"
  value       = module.customer_telemetry.product_urn
}
